spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.35.14.52:3306/jjhotel?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect  # 여기에 Dialect 추가
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
        show_sql: true
        
  mail:
    host: smtp.gmail.com
    port: 587
    username: conn0204 # 3
    password: bkqq tqot yugb nmpl
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true


